version: "3.8"
services:
  test2.7:
    image: public.ecr.aws/lambda/ruby:2.7
    entrypoint: ./bin/_test
    volumes:
      - $PWD:/var/task
    depends_on:
      - postgresql
    links:
      - postgresql
  postgresql:
    image: docker pull postgres:13.6-alpine
    environment:
      - POSTGRESQL_ROOT_PASSWORD=root
